#server
server:
  port: 80
  servlet:
   context-path: /
  tomcat:
    threads:
      max: 128
    uri-encoding: UTF-8
#spring 
spring:
  datasource:
    url: jdbc:mysql:///dbms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 50
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false  #false表示为目标对象基于JDK方式产生代理对象
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        keep-alive: 60000
        queue-capacity: 256
      thread-name-prefix: db-service-thread-
#mybatis
mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml

shiro:
  loginUrl: /doLoginUI
  rememberMeManager:
          cookie:
            name: shiroRememberMe
            maxAge: 3600
            path: /
  userNativeSessionManager: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false
#log
logging:
  level:
    com.cy: debug

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"




